apiVersion: v1
kind: Service
metadata:
  name: {{ include "ziti-webhook.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ziti-webhook.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ziti-webhook.selectorLabels" . | nindent 4 }}
    app: ziti-admission-webhook
  ports:
    - name: https
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
